blank_issues_enabled: true
contact_links:
  - name: CronCoin Core Security Policy
    url: https://github.com/croncoin/croncoin/blob/master/SECURITY.md
    about: View security policy
  - name: CronCoin Core Developers
    url: https://croncoincore.org
    about: CronCoin Core homepage
